const wordList = [
    {
        "word": "abide",
        "synonyms": [
            "endure",
            "put up with",
            "support",
            "stand",
            "stick out",
            "brook",
            "tolerate",
            "suffer",
            "stomach",
            "digest",
            "bear"
        ]
    },
    {
        "word": "absent",
        "synonyms": [
            "devoid",
            "lacking",
            "nonexistent",
            "wanting",
            "truant",
            "gone",
            "awol",
            "departed",
            "missing",
            "introuvable",
            "away"
        ]
    },
    {
        "word": "adventurous",
        "synonyms": [
            "audacious",
            "swaggering",
            "brave",
            "swashbuckling",
            "daring",
            "venturous",
            "adventuresome",
            "courageous",
            "venturesome",
            "incautious",
            "sporting",
            "bold"
        ]
    },
    {
        "word": "aggressive",
        "synonyms": [
            "predatory",
            "ravening",
            "rapacious",
            "scrappy",
            "vulturine",
            "offensive",
            "raptorial",
            "combative",
            "assertive",
            "battleful",
            "bellicose",
            "hostile",
            "self-asserting",
            "competitive",
            "high-pressure",
            "obstreperous",
            "rough",
            "vulturous",
            "militant",
            "pugnacious",
            "truculent",
            "in-your-face",
            "self-assertive",
            "hard-hitting"
        ]
    },
    {
        "word": "alert",
        "synonyms": [
            "wide-awake",
            "vigilant",
            "open-eyed",
            "lively",
            "awake",
            "heads-up",
            "sleepless",
            "on the job",
            "on the alert",
            "argus-eyed",
            "fly",
            "wary",
            "lidless",
            "wakeful",
            "watchful"
        ]
    },
    {
        "word": "annoying",
        "synonyms": [
            "nettlesome",
            "plaguy",
            "vexatious",
            "disagreeable",
            "pesky",
            "teasing",
            "irritating",
            "pestiferous",
            "plaguey",
            "galling",
            "bothersome",
            "vexing",
            "pestering"
        ]
    },
    {
        "word": "modern",
        "synonyms": [
            "current",
            "recent",
            "ultramodern",
            "contemporary",
            "new",
            "neo",
            "red-brick",
            "modern-day",
            "late",
            "moderne",
            "redbrick"
        ]
    },
    {
        "word": "morning",
        "synonyms": [
            "sunup",
            "dawn",
            "break of the day",
            "dayspring",
            "sunrise",
            "first light",
            "break of day",
            "cockcro",
            "aurora",
            "dawning",
            "daybreak"
        ]
    },
    {
        "word": "timid",
        "synonyms": [
            "mousy",
            "coy",
            "shy",
            "afraid",
            "fearful",
            "timorous",
            "trepid",
            "mousey",
            "backward",
            "unadventurous",
            "unassertive",
            "cowardly",
            "bashful",
            "intimidated"
        ]
    },
    {
        "word": "insane",
        "synonyms": [
            "half-crazed",
            "bats",
            "unstable",
            "raving mad",
            "loony",
            "mad",
            "hebephrenic",
            "nuts",
            "maniacal",
            "loco",
            "non compos mentis",
            "unreasonable",
            "crazed",
            "dotty",
            "around the bend",
            "psychopathic",
            "demented",
            "cracked",
            "crackbrained",
            "amok",
            "balmy",
            "fruity",
            "nutty",
            "crazy",
            "unhinged",
            "deranged",
            "paranoid",
            "bonkers",
            "daft",
            "unsound",
            "screw-loose",
            "round the bend",
            "touched",
            "crackers",
            "fey",
            "demoniac",
            "certifiable",
            "buggy",
            "disturbed",
            "possessed",
            "unbalanced",
            "mentally ill",
            "psychopathological",
            "kookie",
            "maniac",
            "loopy",
            "demoniacal",
            "maniclike",
            "psychopathologic",
            "manic-depressive",
            "raving",
            "screwy",
            "of unsound mind",
            "barmy",
            "psychotic",
            "wild",
            "berserk",
            "haywire",
            "amuck",
            "distracted",
            "sick",
            "certified",
            "moonstruck",
            "schizophrenic",
            "batty",
            "brainsick",
            "lunatic",
            "kooky",
            "whacky",
            "irrational",
            "idiotic",
            "wacky"
        ]
    },
    {
        "word": "useless",
        "synonyms": [
            "unserviceable",
            "futile",
            "otiose",
            "unusable",
            "unavailing",
            "ineffectual",
            "unprofitable",
            "uneffective",
            "inutile",
            "unuseable",
            "ineffective"
        ]
    },
    {
        "word": "yucky",
        "synonyms": [
            "repellant",
            "wicked",
            "disgusting",
            "loathsome",
            "repellent",
            "revolting",
            "repelling",
            "skanky",
            "foul",
            "distasteful",
            "loathly",
            "offensive",
            "disgustful"
        ]
    },
]
